# spring.application.name=springbootbootcamp 
#spring.datasource.url=  jdbc:mysql://root:nStamSjnSYJhchyPnyQIrVkrOlxsMyef@mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=nStamSjnSYJhchyPnyQIrVkrOlxsMyef
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#logging.level.org.springframework.security=DEBUG
#spring.security.user.name=disabled
#spring.security.user.password=disabled
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
#spring.profiles.active=prod
##spring.profiles.active=local
##spring.profiles.active=local
#
#
#server.port=8080
#logging.level.org.springframework.core.env=DEBUG
#
# 

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/bootcamp
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
