spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
publisher.secret.code=${PUBLISHER_SECRET_CODE}
server.port=${PORT:8080}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2
