spring.profiles.active=local

spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:59771/railway
spring.datasource.username=root
spring.datasource.password=nStamSjnSYJhchyPnyQIrVkrOlxsMyef

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
